### ISSUE TITLE
getConfig() is being called early in controller if getParameters() is called.

### ISSUE THREAD

**Issue by jcloutz** [neomerx/limoncello#5]
I just found some strange behaviour in the execution order of `JsonApiTrait`.

Assuming the following methods added to the base controller:

```
// Controller.php
protected function setSchema($schemas = [])
{
    $this->schema = $schemas;
}

protected function getConfig()
{
    $config = $this->getIntegration()->getConfig();
    $this->schema === null ?: $config[C::SCHEMAS] = array_merge($config[C::SCHEMAS], $this->schema);

    return $config;
}
```

```
// AuthorsController.php
public function show(Request $request, $id, $type)
{
    // this causes getConfig to be called early
    $params = $this->getParameters();
    
    $this->setSchema([
        Post::class => function ($factory, $container) {
            $schema = new PostSchema($factory, $container);
            $schema->renderAsRelation = true;

            return $schema;
        },
    ]);

    return $this->getContentResponse(Author::findOrFail($id)->getPosts());
    }
}
```

If `getParameters()` is called inside a controller action before `setSchema()`
then `getConfig()` is also called before the schema can be injected into the 
config array.

**Comment by neomerx** [comment]
The root of the problem is that this trait is trying to be helpful (maybe too much :smile:)

When ```getParameters``` is called it works this way
- it needs parameters from URL and controller configuration to compare (no problem here)
- it decodes media types of received data (```Content-Type``` header) and requested (```Accept``` header). Then it wants to check if those types are supported (**that's the root of the problem**). It takes all registered encoders and decoders, finds best matching media types, encoder and decoder. While doing this it instantiates encoder (in ```EncoderMatcher::matchEncoder```) (**that's likely unnecessary thing to do**) which leads to ```getConfig``` call.

#### What are the possible solutions?

Firstly I feel coupling between parameter parsing and matching encoder/decoder has to be changed. It doesn't look beautiful to intercept it with overriding ```getConfig``` when a developer actually wants to say 'use this encoder' or 'use these encoder settings'.

I think ```getParameters``` should parse and check URL parameters and media types in headers however encoder and decoder should not be instantiated. A developer should have an option to modify encoder/decoder/their settings before ```getContentResponse``` is called. For example
- get media types (requested/matched) and set new encoder/decoder (object or closure)
- get media types (requested/matched) and set parameters that will be sent on closure call

I tend to think the first variant is more flexible. In pseudo-code it might be
```php
    if ($this->getEncoderMediaType()->getType() === 'application/vnd.api+json') {
        $this->setEncoder(Encoder::instance([
            Author::class  => AuthorSchema::class,
           ...
        ]);
    }
```

What do you think?

**Comment by jcloutz** [comment]
This works for me, and it makes more sense to be able to inject your own encoder vs just overriding an element in the config array.

**Comment by neomerx** [comment]
Nice to hear it :smile:
